defaultStats = {
    explode_on_death = false,
    wall_slide_on = false,
    ground_pound_dive_on = false,
    ground_pound_jump_on = false,
    ground_pound_jump_dive_on = false,
    disable_double_jump = false,
    twirling_dive_on = false,
    triple_jump_twirling_on = false,
    fast_twirling_on = false,
    back_flip_twirling_on = false,
    side_flip_twirling_on = false,
    twirling_ground_pound_on = false,
    disable_twirling_land = false,
    disable_breath_heal = false,
    disable_burning = false,
    disable_damage = false,
    disable_coin_heal = false,
    one_hit = false,
    mr_l_jump_on = false,
    play_mr_l_anticipation_audio = true,
    saultube_jump_animation = false,
    saultube_single_jump_animation = false,
    saultube_double_jump_animation = false,
    saultube_triple_jump_animation = false,
    kick_dive_on = false,
    glide_dive_on = false,
    glide_dive_render_with_wing_cap = false,
    glide_dive_disable_spin = false,
    long_jump_triple_jump_on = false,
    super_side_flip_on = false,
    yoshi_flutter_on = false,
    kill_toad = false,
    kill_pink_bomb_on = false,
    peel_out_on = false,
    peel_out_jump_reset_vel = true,
    disable_fall_damage =  false,
    always_dive_first = false,
    dive_kick_on =  false,
    dive_ground_pound_on = false,
    sonic_jump_on = false,
    wall_slide_same_wall = false,
    charge_sonic_dash_on = false,
    drop_dash_on = false,
    disable_special_triple_jump_bounce = false,
    ground_pound_dive_change_direction_on = false,
    special_triple_jump_on = false,
    mushroom_allergy = false,
    -- Umbrella Glide Defaults
    chaorrin_umbrella_glide_on = false,
    chaorrin_umbrella_animation = "default",
    chaorrin_umbrella_max_timer = 999,
    chaorrin_umbrella_vertical_speed = 5,
    chaorrin_umbrella_glide_forward_speed = 100,
    chaorrin_umbrella_caps_forward_speed = true,
    -- Honey Queen Fly Defaults
    honeyQueen_fly_on = false,
    honeyQueen_fly_render_cap = true,
    honeyQueen_max_fly_timer = 80,
    honeyQueen_render_hud = true,
    honeyQueen_fly_animation = "default",
    honeyQueen_fly_forward_speed = 100,
    honeyQueen_fly_strength = 100,
    hide_barrel_on= false,
    -- Change barrel type from 'barrel', 'substitute', 'box'
    hide_barrel_type = "barrel",
    -- wall_slide_jump_type can be ACT_JUMP, ACT_DIVE, ACT_TRIPLE_JUMP, ACT_TWIRLING, ACT_SIDE_FLIP
    wall_slide_jump_type = ACT_JUMP,
    -- shell_slide lets the character slide inside shell, it needs bowser moveset, it executes by crouching while running
    bowser_shell_slide = true,
    -- bowser_fire_ball it lets you shoot fire while crouching and not moving and needs bowser moveset
    bowser_fire_ball = true,
    -- bowser_punch lets you use custom bowser animation and needs bowser moveset
    bowser_punch = true,
    -- bowser_shell_model change shell_slide model and needs bowser moveset
    -- Options: "bowser", "koopakid", "bowserjr", "koopalings_m", "koopalings_s", "koopalings_l", "koopalings_xl" or you can write the geo model
    bowser_shell_model = "bowserjr"
}